; ---------------------------------------------------------------------------
; This demo shows how to use engine-provided services:
;    * draw tiled images
; Notes:
;   - Tiled (https://www.mapeditor.org/) is a 3rd party editor used to produce
;     the tiled image source files (tmj).
;   - The tiled image source file and the exported asset can contain multiple
;     layers that reference one tile graphics.
;   - The game engine library represents one tmj files as two separate assets:
;     the index data and the tile graphics. This separation allows for more
;     efficient memory usage and asset management.
;     The index data is represented by the `tiled_img_data` type (*`_data.json`)
;     asset, while the tile graphics are represented by the `tiled_img_gfx` type
;     (*`_gfx.json`) asset. Both files reference the `tiled_img` type source
;     file that contains general metadata and reference to tmj.
;   - Each tmj layer is converted into separate index data within the
;     `tiled_img_data` asset. Labels that reference each layer index data are
;     stored in the generated index data metadata (`*_data_meta.asm`) file.
;   - This demo uses the `RAM_DISK_OFF_CMD` RAM-disk access command because
;     the data doesn't require copying from the RAM disk.
;   - For ROM executables: to reduce memory footprint, you would want to compress
;     the data, link it to the ROM, uncompress it to the RAM disk at runtime,
;     and then draw it with a proper RAM disk access command.
;   - For COM executables: to reduce memory footprint, consider loading assets
;     from the FDD at runtime instead of keeping everything included to ROM file.
; ---------------------------------------------------------------------------

; ---------------------------------------------------------------------------
; Tiled Image asset format:
;   The source asset is a JSON file that contains fields:
;	  "path_png"     - path to the PNG file containing the tiled image graphics
;	  "palette_path" - path to the JSON file containing the palette data
;	  "asset_type"   - tiled_img
;	  "path"         - path to tmj (Tiled format output) file.
; ---------------------------------------------------------------------------

; ---------------------------------------------------------------------------
; Tiled Image index data asset format:
;   The source asset is a JSON file that contains fields:
;     "asset_type"     - tiled_img_data
;     "path_tiled_img" - path to the Tiled image data (json), in this case "tim.json"
; ---------------------------------------------------------------------------

; ---------------------------------------------------------------------------
; Tiled Image tile graphics asset format:
;   The source asset is a JSON file that contains fields:
;     "asset_type"     - tiled_img_gfx
;     "path_tiled_img" - path to the Tiled image data (json), in this case "tim.json"
; ---------------------------------------------------------------------------

; ---------------------------------------------------------------------------
; Tiled Image index data metadata format:
;   The *data_meta.asm file is generated by the exporter and contains labels
;   with local offsets to tiled image layers index data used by the drawing
;   routine. It also can contain the filename and the file length used by COMs.
; ---------------------------------------------------------------------------

; ---------------------------------------------------------------------------
; Tiled Image tile graphics metadata format:
;   The graphics *gfx_meta.asm file exposes the same file-size information for
;   the graphics blob and can also conain the file name used by COM executibles.
; ---------------------------------------------------------------------------

; ---------------------------------------------------------------------------
; Tiled Image index data data format:
;   The *data_data.asm file is generated by the exporter and contains:
;   - Two safety pair of bytes before each layer index clock.
;   - The layers. Each layer contains:
;     - `word` - layer data len to copy to the temp buffer.
;     - `.word` - screen address (left-bottom corner)
;     - `.word` - screen address end (right-top corner)
;     - The compressed index data. The maximum number of gfx tiles is 254, because
;       0 and $FF idxs are reserved. 0 is a transparent tile, and $FF is the
;       repeater code, meaning the next two bytes represent the idx and repeating
;       counter.
; ---------------------------------------------------------------------------

; ---------------------------------------------------------------------------
; Tiled Image tile graphics data format:
;   - The *gfx_data.asm file is generated by the exporter contains raw 8x8 pixel
;     tile graphics and two safety bytes before each tile.
;   - The palette required for this tile graphics is specified in the
;     `palette_path` field of the tiled image asset (`tiled_img` type). It is a
;     separate asset and must be properly exported, and linked to the project.
; ---------------------------------------------------------------------------

; ---------------------------------------------------------------------------
; Text Ex API
;  `text_ex_reset_spacing` - reset line and paragraph spacing to default values.
;  `text_ex_set_spacing`   - set line and paragraph spacing
;                            (C = line spacing, B = paragraph spacing).
;  `text_ex_set_scr_addr`  - set the high byte of screen buffer address (A =
;                            >SCR_BUFF3_ADD, >SCR_BUFF2_ADDR, >SCR_BUFF1_ADDR,
;                            default >SCR_BUFF1_ADDR).
;  `text_ex_init_font`     - initialize the font graphics data (A = RAM disk
;                            access command, HL = font_gfx_ptrs, BC = font global
;                            gfx addr, points to where gfx was loaded or linked).
;  `text_ex_init_text`     - initialize the text data (A = RAM disk access
;                            command, HL = text data addr, points to the addr
;                            where it was loaded or linked).
;  `text_ex_draw`          - draw the text (DE = local text addr within the text
;                            data blob).
;  `text_ex_draw_pos_offset_set` - drawing the text with a position offset (DE =
;                            local text addr within the text data blob, HL =
;                            scr_pos offset).
; ---------------------------------------------------------------------------

; Import engine constants, helper macros, and text drawing routines.
.include "../../engine/common/v6_consts.asm"
.include "../../engine/common/v6_macros.asm"
.include "../../engine/gfx/v6_text_ex_consts.asm"

; Include generated metadata for tiled image data and palette.
.include "build/05_text_ex/fonts/asm/font_meta.asm"
.include "build/05_text_ex/text/asm/txt_menu_meta.asm"
.include "build/04_tiled_img/palettes/asm/pal_lv1_meta.asm"

.global main

main:
            ; Fade in animation from the constant color to the exported palette.
            lxi d, _pal_lv1 + _pal_lv1_palette_fade_to_black_relative
            call palette_fade_reverse

            A_TO_ZERO(RAM_DISK_OFF_CMD)
            lxi h, font_gfx_ptrs
            lxi b, _font
            call text_ex_init_font

            A_TO_ZERO(RAM_DISK_OFF_CMD)
            lxi h, _txt_menu
            call text_ex_init_text

            mvi a, >SCR_BUFF2_ADDR
            call text_ex_set_scr_addr

            lxi d, _main_menu_license
			call text_ex_draw

            ret
