echo off

echo This is the demonstration of how to build a music demo using the v6 library,
echo and include the song data in the ROM image.
echo Demo logic is in assembly language.
echo .


rem === UPDATE PATHS ===========================================================
rem Tools paths.
set v6asm=C:\Work\Programming\v6asm\target\release\v6asm
set zx0=tools\zx0\zx0salvador.exe -classic
set compiler=C:\Work\Programming\v6llvmc\llvm-build\bin\clang
set emu=C:\Work\Programming\devector\bin\devector

set CURRENT_DIR=%~dp0
for %%I in ("%CURRENT_DIR:~0,-1%") do set "PROJECT_NAME=%%~nxI"
set OUT_DIR=build\%PROJECT_NAME%


rem === Build the assets =======================================================
rem Compile the song data and compress it using the tools/zx0/ compressor.
rem --emit-asm flag is not necessary and used here just for demonstration purposes,
rem to show the middle assembly code generated by the v6gel exporter.
python -m v6gel.cli.v6export ^
    %CURRENT_DIR%assets\music\song01.json ^
    -o %OUT_DIR%\music\meta ^
    --bin-dir %OUT_DIR%\music\bin ^
    --emit-asm

set song=%OUT_DIR%\music\bin\song01.o


rem === Build the v6 library ===================================================
engine\build.bat
set v6=build\v6\v6.o


rem === Assemble the main file =================================================
%v6asm% main.asm -o %OUT_DIR%\main.o -f obj


echo === Link the main program with the v6 library and the song data. ==========
set target=-target i8080-unknown-v6c
set STACK_MAIN_PROGRAM_ADDR=0x100
set STACK_DEF=-Wl,--defsym=__stack_top=%STACK_MAIN_PROGRAM_ADDR%

%compiler% %target% -O2 %STACK_DEF% ^
    %OUT_DIR%\main.o %v6% %song% ^
    -o %OUT_DIR%\main.rom
if %errorlevel% neq 0 exit /b %errorlevel%


echo === Run the ROM in the emulator. ==========================================
rem Run the ROM in the emulator.
%emu% %OUT_DIR%\main.rom