@echo off

echo.
echo === Description ===========================================================
echo TODO:
echo Demo logic is in assembly language.


echo.
echo === TOOLS PATHS (update if required) ======================================
set v6asm=C:\Work\Programming\v6asm\target\release\v6asm
set zx0=tools\zx0\salvador.exe -classic
set compiler=C:\Work\Programming\v6llvmc\llvm-build\bin\clang
set emu=C:\Work\Programming\devector\bin\devector
echo %v6asm%
echo %zx0%
echo %compiler%
echo %emu%

rem === Set the current directory to the location of this script. ==============
set CURRENT_DIR=%~dp0
for %%I in ("%CURRENT_DIR:~0,-1%") do set "PROJECT_NAME=%%~nxI"
set OUT_DIR=build\%PROJECT_NAME%


echo.
echo === Build the assets ======================================================


echo.
rem export music: song01
rem v6export compiles the song data and compresses it (tools/zx0/ compressor).
rem --emit-asm flag is not necessary and used here just for demonstration purposes,
rem to show the middle assembly code generated by the v6gel exporter.
set song01_json=%CURRENT_DIR%assets\music\song01.json
set song_o=%OUT_DIR%\music\bin\song01.o
echo asset: %song01_json%
python -m v6gel.cli.v6export ^
    %song01_json% ^
    -o %OUT_DIR%\music\meta ^
    --bin-dir %OUT_DIR%\music\bin ^
    --emit-asm ^
    --emit-obj ^
    --compress


echo.
rem export palette: pal_lv1
rem It contains 16 byte palette data and fade animation sequence data.
rem --emit-asm flag is used here for demonstrating the data format.
set pal_lv1_json=%CURRENT_DIR%assets\palettes\pal_lv1.json
set pal_lv1_o=%OUT_DIR%\palettes\bin\pal_lv1.o
echo asset: %pal_lv1_json%
python -m v6gel.cli.v6export ^
    %pal_lv1_json% ^
    -o %OUT_DIR%\palettes\meta ^
    --bin-dir %OUT_DIR%\palettes\bin ^
    --emit-asm ^
    --emit-obj


echo.
rem export sprite: knight
rem It contains 16x16 pixel sprite data and animation sequence data.
rem --emit-asm flag is used here for demonstrating the data format.
set knight_json=%CURRENT_DIR%assets\sprites\knight.json
set knight_o=%OUT_DIR%\sprites\bin\knight.o
echo asset: %knight_json%
python -m v6gel.cli.v6export ^
    %knight_json% ^
    -o %OUT_DIR%\sprites\meta ^
    --bin-dir %OUT_DIR%\sprites\bin ^
    --emit-asm ^
    --emit-obj


echo.
echo === Build the v6 library ==================================================
set v6_o=build\v6\v6.o
rem --symbols flag is used here for demonstration purposes to show the symbols
rem in the v6 library. They will be stored to build\v6\v6.symtab file.
pushd .
call engine\build.bat --symbols
popd
if %errorlevel% neq 0 exit /b %errorlevel%

echo.
echo === Assemble the main file ================================================
%v6asm% %CURRENT_DIR%main.asm -o %OUT_DIR%\main\main.o -f obj
if %errorlevel% neq 0 exit /b %errorlevel%


echo.
echo === Link the main program with the v6 library and the song data. ==========
set target=-target i8080-unknown-v6c
set STACK_MAIN_PROGRAM_ADDR=0x100
set STACK_DEF=-Wl,--defsym=__stack_top=%STACK_MAIN_PROGRAM_ADDR%

%compiler% %target% %STACK_DEF% -nostdlib -O2 ^
    %OUT_DIR%\main\main.o ^
    %v6_o% ^
    %song_o% ^
    %pal_lv1_o% ^
    %knight_o% ^
    -o %OUT_DIR%\%PROJECT_NAME%.rom
if %errorlevel% neq 0 exit /b %errorlevel%


echo.
echo === Run the ROM in the emulator ===========================================
rem Run the ROM in the emulator.
%emu% %OUT_DIR%\%PROJECT_NAME%.rom